import { createTheme } from '@uiw/codemirror-themes'
import { tags as t } from '@lezer/highlight'
import { Extension } from '@uiw/react-codemirror'

export const synthwave84Theme:Extension = createTheme({
	theme: 'dark',
	settings: {
		background: '#262335',
		foreground: '#BBBBBB',
		selection: '#fff1',
		lineHighlight: 'rgba(255, 255, 255, 3%)',
		caret: '#F97E72',
		selectionMatch: '#B9A0FF55',
		gutterForeground: '#BBB',
		gutterBackground: '#222232',
	},
	styles: [
		{ tag: t.keyword, color: '#FEDE5C' },
		{ tag: t.variableName, color: '#FF7EDB' },
		{ tag: t.name, color: '#31DED9' },
		{ tag: t.string, color: '#FFAC71' },
		{ tag: t.standard(t.tagName), color: '#DB2F63' },
		{ tag: t.tagName, color: '#4DCDAC' },
		{ tag: t.angleBracket, color: '#36EFD1' },
		{ tag: t.attributeName, color: '#FEDE5C' },
		{ tag: t.className, color: '#DB2F63' },
		{ tag: t.comment, color: '#848AB9' },
		{ tag: t.bracket, color: '#FEDE5D' },
		{ tag: t.operator, color: '#FEDE5D' },
		{ tag: t.punctuation, color: '#FEDE8D' },
		{ tag: t.definition(t.punctuation), color: '#BBB' },
		{ tag: t.separator, color: '#BBBBBB' },
		{ tag: t.derefOperator, color: '#BBBBBB' },
		{ tag: t.definitionOperator, color: '#F0EFF1' },
		{ tag: t.literal, color: '#F97E72' },
		{ tag: t.meta, color: '#BBB' },
		{ tag: t.self, color: '#BBB' },
		{ tag: t.link, color: '#BBB' },
		{ tag: t.special(t.variableName), color: '#F97E72' },
		{ tag: t.escape, color: '#36EFD1' },
		{ tag: t.contentSeparator, color: '#BBB' },
		{ tag: t.heading4, color: 'red' },
		{ tag: t.heading, color: '#54f' },
		{ tag: t.special(t.string), color: '#F97E72' },
	],
})
